language: python

jobs:
  include:
    - name: "py3.5"
      python: 3.5

    - name: "py3.6"
      python: 3.6

    - name: "py3.7"
      python: 3.7

    - name: "py3.7 with PyQt5"
      python: 3.7
      sudo: required
      before_install:
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash ./miniconda.sh -b -p ${HOME}/miniconda;
        export PATH=${HOME}/miniconda/bin:$PATH;
        conda install --yes python="3.7" pyqt="5.9";
        pip install pytest;

    - name: "py3.8"
      python: 3.8

install:
  - pip install pytest-cov
  - pip install -e .
  - pip install coveralls

script:
  #- coverage run --source=src -m pytest
  - pytest --cov src
    
after_sucess:
  - coverage combine .coverage
  - coverage report -m
  - coveralls