language: python

jobs:
  include:
    - name: "py3.6"
      python: 3.6

    - name: "py3.7"
      python: 3.7

    - name: "py3.7 miniconda with PyQt5"
      python: 3.7
      before_install:
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash ./miniconda.sh -b -p ${HOME}/miniconda;
        export PATH=${HOME}/miniconda/bin:$PATH;
        conda install --yes python="3.7" pyqt="5.9";

    - name: "py3.8"
      python: 3.8

install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install -e .[dev]

script:
  #- coverage run -p --source=src -m pytest
  #- PYTHONPATH=src pytest --cov src --cov-append
  - COVERALLS_PARALLEL=true coveralls
  - pytest --cov src --cov-append
    
after_success:
  - coverage combine
  #- coverage combine .coverage
  - coverage report -m
  - coveralls